<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


<h3>Train test split</h3>

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

2334                    What happen to her tell the truth
5247    Gud ni8 dear..slp well..take care..swt dreams....
1619    The 2 oz guy is being kinda flaky but one frie...
3008    Ah you see. You have to be in the lingo. I wil...
Name: Message, dtype: object

In [25]:
X_train.loc[2334]

'What happen to her tell the truth'

In [12]:
type(y_train)

pandas.core.series.Series

In [13]:
y_train[:4]

2334    0
5247    0
1619    0
3008    0
Name: spam, dtype: int64

In [14]:
type(X_train.values)

numpy.ndarray

<h3>Create bag of words representation using CountVectorizer</h3>

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59605 stored elements and shape (4457, 7757)>

In [16]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7757,))

In [17]:
X_train_cv.shape

(4457, 7757)

In [22]:
v.get_feature_names_out()[7481]

'what'

In [19]:
v.vocabulary_

{'what': 7481,
 'happen': 3334,
 'to': 6936,
 'her': 3420,
 'tell': 6753,
 'the': 6811,
 'truth': 7064,
 'gud': 3270,
 'ni8': 4762,
 'dear': 2196,
 'slp': 6236,
 'well': 7459,
 'take': 6690,
 'care': 1658,
 'swt': 6665,
 'dreams': 2449,
 'muah': 4632,
 'oz': 5035,
 'guy': 3289,
 'is': 3763,
 'being': 1308,
 'kinda': 3958,
 'flaky': 2881,
 'but': 1580,
 'one': 4934,
 'friend': 3004,
 'interested': 3721,
 'in': 3659,
 'picking': 5189,
 'up': 7181,
 'lt': 4256,
 'gt': 3264,
 'worth': 7614,
 'tonight': 6972,
 'if': 3618,
 'possible': 5315,
 'ah': 869,
 'you': 7717,
 'see': 5980,
 'have': 3366,
 'be': 1271,
 'lingo': 4141,
 'will': 7525,
 'let': 4098,
 'know': 3979,
 'wot': 7616,
 'on': 4930,
 'earth': 2512,
 'it': 3775,
 'when': 7488,
 'has': 3352,
 'finished': 2858,
 'making': 4334,
 'wonder': 7585,
 'how': 3536,
 'got': 3204,
 'online': 4938,
 'my': 4664,
 'love': 4233,
 'had': 3300,
 'gone': 3185,
 'net': 4740,
 'cafe': 1600,
 'did': 2300,
 'get': 3123,
 'your': 7722,
 'phone': 5174,
 '

In [20]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7757,))

In [27]:
X_train_np[0][3334]

np.int64(1)

In [21]:
np.where(X_train_np[0]!=0)

(array([3334, 3420, 6753, 6811, 6936, 7064, 7481]),)

In [29]:
X_train_np[0][3334]

np.int64(1)

<h3>Train the naive bayes model</h3>

In [30]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [31]:
X_test_cv = v.transform(X_test)

<h3>Evaluate Performance</h3>

In [33]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       961
           1       0.97      0.93      0.95       154

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [34]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [35]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [36]:
clf.fit(X_train, y_train)

,steps,"[('vectorizer', ...), ('nb', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [37]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       961
           1       0.97      0.93      0.95       154

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

