In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a[0]

np.int64(1)

In [6]:
import time
import sys

l=list(range(1000))
print(sys.getsizeof(l[0])*len(l))

24000


In [5]:
a=np.arange(1000)
print(a.size*a.itemsize)

8000


# Time

In [7]:
size=1000

In [8]:
l1=list(range(size))
l2=list(range(size))
start=time.time()
result=[x+y for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

0.19621849060058594


In [9]:
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=a1+a2
print((time.time()-start)*1000)

2.902984619140625


In [10]:
size=10000000

In [11]:
l1=list(range(size))
l2=list(range(size))
start=time.time()
result=[x+y for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

702.8889656066895


In [12]:
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=a1+a2
print((time.time()-start)*1000)

133.6498260498047


# operations

In [13]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])


In [14]:
a1+a2

array([5, 7, 9])

In [15]:
a1-a2

array([-3, -3, -3])

In [16]:
a1/a2

array([0.25, 0.4 , 0.5 ])