In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a[0]

np.int64(1)

In [4]:
b=np.array([[1,2],[3,4],[5,6]])
b[0]

array([1, 2])

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.itemsize

8

In [8]:
b.itemsize

8

In [9]:
a.dtype

dtype('int64')

In [10]:
a=np.array([[1,2],[3,4]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.]])

In [11]:
a.itemsize

8

In [12]:
a.size

4

In [13]:
len(a)

2

In [14]:
a.shape

(2, 2)

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((2,))

array([0., 0.])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.ones((3,))

array([1., 1., 1.])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,5,2)

array([1, 3])

In [22]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [26]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [29]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
a.min()

np.int64(1)

In [32]:
a.max()

np.int64(6)

In [33]:
a.sum()

np.int64(21)

In [34]:
a.sum(axis=0)

array([ 9, 12])

In [36]:
a.sum(axis=1)

array([ 3,  7, 11])

In [37]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [38]:
np.std(a)

np.float64(1.707825127659933)

In [39]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [40]:
a+b

array([[ 6,  8],
       [10, 12]])

In [41]:
a-b

array([[-4, -4],
       [-4, -4]])

In [42]:
a*b

array([[ 5, 12],
       [21, 32]])

In [43]:
a.dot(b)

array([[19, 22],
       [43, 50]])