In [1]:
import numpy as np

In [2]:
n=[6,7,8]
n[0:2]

[6, 7]

In [3]:
n[-1]

8

In [4]:
a=np.array([1,2,3,4,5])
a[0:2]

array([1, 2])

In [5]:
a[-1]

np.int64(5)

In [6]:
a=np.array([
    [6,7,8],
    [1,2,3],
    [9,4,5]
])

In [7]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 4, 5]])

In [8]:
a[0]

array([6, 7, 8])

In [9]:
a[0,2]

np.int64(8)

In [10]:
a[1,:]

array([1, 2, 3])

In [11]:
a[0:2,1]

array([7, 2])

In [12]:
a[:,0:2]

array([[6, 7],
       [1, 2],
       [9, 4]])

In [13]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [4, 5]])

In [14]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 4, 5]])

In [15]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 4 5]


In [17]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 4, 5]])

In [19]:
for cell in a.ravel():
    print(cell)

6
7
8
1
2
3
9
4
5


In [20]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
4
5


In [21]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [27]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [28]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [29]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [31]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a>4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [34]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
a[a>4]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])