- Numpy slicing is similar to python lists.
- Multi-dimensional indexing is powerful.
- Boolean indexing is fast and efficient
- widely used in Data science and Scientific Computing


###  remember during indexing and slicing ,we always start from 0 and we exclude the last 

In [1]:
import numpy as np

In [2]:
n=[6,7,8]
n[0:2]

[6, 7]

In [3]:
n[-1]

8

### for 1D-> same as python lists

In [4]:
a=np.array([1,2,3,4,5])
a[0:2]

array([1, 2])

In [5]:
a[-1]

np.int64(5)

#### Indexing in multidimensional numpy arrays is little different from regular python lists

In [6]:
a=np.array([
    [6,7,8],
    [1,2,3],
    [9,4,5]
])

In [7]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 4, 5]])

In [8]:
a[0]

array([6, 7, 8])

In [ ]:
a[0,2] # 0th row,3rd element

np.int64(8)

#### slicing rows and columns in multidimensional array

In [10]:
a[1,:]

array([1, 2, 3])

In [11]:
a[0:2,1]

array([7, 2])

In [12]:
a[:,0:2]

array([[6, 7],
       [1, 2],
       [9, 4]])

In [13]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [4, 5]])

In [14]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 4, 5]])

#### 4.Iterating through numpy arrays

In [15]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 4 5]


In [17]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 4, 5]])

In [ ]:
for cell in a.ravel(): # or a.flat() but a.ravel()->recommended
    print(cell)

6
7
8
1
2
3
9
4
5


In [20]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
4
5


##### Vertical stacking of arrays (vstack)
- vstack() stacks arrays vertically(one above another)

In [ ]:
a=np.arange(6).reshape(3,2) #- arange + reshape for faster numpy array declaration
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))#vstack() stacks arrays vertically(one above another)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

#### Horizontal stacking of arrays(hstack)
- hstack() stacks arrays side by side

In [25]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

### Horizontal splitting of arrays(hsplit)
- hsplit() divides an array into equal vertical parts(side by side splitting)

In [27]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
np.hsplit(a,3) # 3 partitions

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

### vertical splliting of arrays (vsplit)
- vsplit() divied arrays row-wise (one above another splitting)

In [ ]:
np.vsplit(a,2) # 2 partitions

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

### Boolean indexing in numpy 
- Boolean indexing allows selecting element based on conditions

In [31]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a>4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

### Extracting elements using boolean index
- when boolean array is used as an index,Numpy only returns the 1D of True Elements


In [35]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [34]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

#### Replacing values using Boolean indexing
- we can modify array values using conditions

In [ ]:
a[a>4]=-1 # those values greater than 4 gets replaced
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])