In [1]:
import numpy as np

In [3]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
for row in a:
    print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for x in a.flatten():
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [7]:
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for x in np.nditer(a,order="F"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [9]:
for x in np.nditer(a,order="F",flags=["external_loop"]):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [11]:
for x in np.nditer(a):
    x[...]=2
print(a)

ValueError: assignment destination is read-only

In [12]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x[...]=x*x

print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [14]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x=x*2

print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [15]:
a


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [20]:
b=np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [21]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
4 0
9 0
16 1
25 1
36 1
49 1
64 2
81 2
100 2
121 2


In [25]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 1
4 2
9 3
16 4
25 5
36 6
49 7
64 8
81 9
100 10
121 11
